### ISSUE TITLE
module 'Xlib.ext.shape' has no attribute 'SO'

### ISSUE THREAD

**Issue by jedi2610** [seebye/ueberzug#112]
```
Traceback (most recent call last):
  File "/home/jedi/.local/bin/ueberzug", line 8, in <module>
    sys.exit(main())
  File "/home/jedi/.local/lib/python3.8/site-packages/ueberzug/__main__.py", line 52, in main
    module.main(options)
  File "/home/jedi/.local/lib/python3.8/site-packages/ueberzug/layer.py", line 210, in main
    windows = batch.BatchList(window_factory.create(*window_infos))
  File "/home/jedi/.local/lib/python3.8/site-packages/ueberzug/ui.py", line 60, in create
    return [OverlayWindow(self.display, self.view, info)
  File "/home/jedi/.local/lib/python3.8/site-packages/ueberzug/ui.py", line 60, in <listcomp>
    return [OverlayWindow(self.display, self.view, info)
  File "/home/jedi/.local/lib/python3.8/site-packages/ueberzug/ui.py", line 164, in __init__
    self.create()
  File "/home/jedi/.local/lib/python3.8/site-packages/ueberzug/ui.py", line 234, in create
    self._set_click_through()
  File "/home/jedi/.local/lib/python3.8/site-packages/ueberzug/ui.py", line 287, in _set_click_through
    Xshape.SO.Set, Xshape.SK.Input, 0,
AttributeError: module 'Xlib.ext.shape' has no attribute 'SO'
```

ranger preview suddenly stopped working and i'm getting this error while trying to run `ueberzug layer`

**Comment by seebye** [comment]
Seems like you have an old version of python-xlib installed or some fork like xlib or python3-xlib.  
Uninstall it including ueberzug und reinstall ueberzug..

**Comment by jedi2610** [comment]
alr cool thanks it works
