### ISSUE TITLE
Panic after every few invocations

### ISSUE THREAD

**Issue by Ryujinra** [seebye/ueberzug#35]
Using the following commands:

```
source "`ueberzug library`"
ImageLayer 0< <(
    ImageLayer::add [identifier]="image0" [x]=0 [y]=0 [path]="./test.jpg"
    read
)
```

The image is loaded as expected sporadically, but after every few invocations I receive the following traceback and the image is not loaded:

```
Traceback (most recent call last):
  File "/usr/bin/ueberzug", line 11, in <module>
    load_entry_point('ueberzug==18.1.2', 'console_scripts', 'ueberzug')()
  File "/usr/lib/python3.7/site-packages/ueberzug/ueberzug.py", line 225, in main
    main_layer(options)
  File "/usr/lib/python3.7/site-packages/ueberzug/ueberzug.py", line 181, in main_layer
    windows = batch.BatchList(window_factory.create(*window_infos))
  File "/usr/lib/python3.7/site-packages/ueberzug/ui.py", line 66, in create
    for info in window_infos]
  File "/usr/lib/python3.7/site-packages/ueberzug/ui.py", line 66, in <listcomp>
    for info in window_infos]
  File "/usr/lib/python3.7/site-packages/ueberzug/ui.py", line 163, in __init__
    self._screen.height_in_pixels)
SystemError: <class 'Xshm.Image'> returned NULL without setting an error

```

Tried the release version and building from source. On fully updated Arch machine. Screen is HiDPI (4K) if that is relevant.

Thanks for any help.

**Comment by seebye** [comment]
That's just a assumption as I don't see another place except https://github.com/seebye/ueberzug/blob/master/Xshm/Xshm.c#L114
which returns without setting an error message:  
Did you ran out of memory?

**Comment by Ryujinra** [comment]
I have around 8GB of free memory; I'm not seeing a spike when I run ueberzug either. Odd that it doesn't happen every single time. Sometimes it runs 3 or 4 times without error, and other times I receive the trace back 4 times in a row.

**Comment by sklorpion** [comment]
i've same problem sometimes works, sometimes:
Traceback (most recent call last):
  File "/usr/bin/ueberzug", line 11, in <module>
    load_entry_point('ueberzug==18.1.2', 'console_scripts', 'ueberzug')()
  File "/usr/lib/python3.7/site-packages/ueberzug/ueberzug.py", line 225, in main
    main_layer(options)
  File "/usr/lib/python3.7/site-packages/ueberzug/ueberzug.py", line 181, in main_layer
    windows = batch.BatchList(window_factory.create(*window_infos))
  File "/usr/lib/python3.7/site-packages/ueberzug/ui.py", line 66, in create
    for info in window_infos]
  File "/usr/lib/python3.7/site-packages/ueberzug/ui.py", line 66, in <listcomp>
    for info in window_infos]
  File "/usr/lib/python3.7/site-packages/ueberzug/ui.py", line 163, in __init__
    self._screen.height_in_pixels)
SystemError: <class 'Xshm.Image'> returned NULL without setting an error

**Comment by lettim** [comment]
Same issue for me.
I'm using it with vifm and just randomly see this error when opening vifm with a script in st.

**Comment by seebye** [comment]
Not sure whether it solves this issue, but I used an invalid function signature for the init function of the Xshm.Image object.  
So could you check whether the issue still appears with the current version of the master branch?

**Comment by ertwro** [comment]
Same issue here. Just updated and now it gives me `Xlib: extension "MIT-SHM" missing on display ":0".` when it draws and sometimes the error reported here about `SystemError: class <'Xshm.Image'> retruned NULL without sending error`

**Comment by Ryujinra** [comment]
New traceback from version built from latest source:

`Traceback (most recent call last):
  File "/usr/bin/ueberzug", line 11, in <module>
    load_entry_point('ueberzug==18.1.2', 'console_scripts', 'ueberzug')()
  File "/usr/lib/python3.7/site-packages/ueberzug/ueberzug.py", line 225, in main
    main_layer(options)
  File "/usr/lib/python3.7/site-packages/ueberzug/ueberzug.py", line 181, in main_layer
    windows = batch.BatchList(window_factory.create(*window_infos))
  File "/usr/lib/python3.7/site-packages/ueberzug/ui.py", line 66, in create
    for info in window_infos]
  File "/usr/lib/python3.7/site-packages/ueberzug/ui.py", line 66, in <listcomp>
    for info in window_infos]
  File "/usr/lib/python3.7/site-packages/ueberzug/ui.py", line 163, in __init__
    self._screen.height_in_pixels)
SystemError: <class 'Xshm.Image'> returned NULL without setting an error`

**Comment by chrhasse** [comment]
I was having this issue as well (in ranger on arch with `python-ueberzug` installed), and installing the latest update from git (through `python-ueberzug-git`) seems to have fixed it for me.

**Comment by Ryujinra** [comment]
I removed the previously built tarball and forced a clean build from source and it looks like the issue is fixed for me as well! 

If you are still having issues, ensure you are doing a full, clean build.

I will close this myself if someone else who was still having issues confirms the issue is fixed, or @seebye can close this now if he sees fit, since the tracebacks were identical for others having the same problem.
