### ISSUE TITLE
freebsd issues, freezes and error spitting

### ISSUE THREAD

**Issue by cirala** [seebye/ueberzug#44]
Hello,

I'm trying to get Ueberzug to work on my FreeBSD setup I installed it and everything seemed to be working fine until I tried the following command;

$ source `ueberzug library`

Now whenever I call the "ImageLayer" command used in the bash demo I get this error list:

```
Traceback (most recent call last):
  File "/home/thim/.local/lib/python3.6/site-packages/psutil/_common.py", line 341, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thim/.local/bin/ueberzug", line 11, in <module>
    load_entry_point('ueberzug==18.1.3', 'console_scripts', 'ueberzug')()
  File "/home/thim/.local/lib/python3.6/site-packages/ueberzug/ueberzug.py", line 225, in main
    main_layer(options)
  File "/home/thim/.local/lib/python3.6/site-packages/ueberzug/ueberzug.py", line 175, in main_layer
    window_infos = xutil.get_parent_window_infos()
  File "/home/thim/.local/lib/python3.6/site-packages/ueberzug/xutil.py", line 156, in get_parent_window_infos
    clients_pid_tty = {psutil.Process().pid: None}
  File "/home/thim/.local/lib/python3.6/site-packages/psutil/__init__.py", line 442, in
__init__
    self._init(pid)
  File "/home/thim/.local/lib/python3.6/site-packages/psutil/__init__.py", line 469, in
_init
    self.create_time()
  File "/home/thim/.local/lib/python3.6/site-packages/psutil/__init__.py", line 819, in
create_time
    self._create_time = self._proc.create_time()
  File "/home/thim/.local/lib/python3.6/site-packages/psutil/_psbsd.py", line 561, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/thim/.local/lib/python3.6/site-packages/psutil/_psbsd.py", line 735, in create_time
    return self.oneshot()[kinfo_proc_map['create_time']]
  File "/home/thim/.local/lib/python3.6/site-packages/psutil/_psbsd.py", line 561, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/thim/.local/lib/python3.6/site-packages/psutil/_common.py", line 344, in wrapper
    return fun(self)
  File "/home/thim/.local/lib/python3.6/site-packages/psutil/_psbsd.py", line 618, in oneshot
    ret = cext.proc_oneshot_info(self.pid)
SystemError: NULL object passed to Py_BuildValue

```

Image previews are obviously not working and I may be missing something here but if anyone has any ideas that'd be great. Cheers

**Comment by seebye** [comment]
I'm closing this issue as it's an issue of psutil.
psutil seems not to be able to obtain the process information of the process it's executed in.
