### ISSUE TITLE
Python-Pillow-Simd Update

### ISSUE THREAD

**Issue by dmorady1** [seebye/ueberzug#47]
Hello Together,
I use ueberzug with vifm and it worked just fine. Then i unconscious update my packages and simd was in it. So now i have the problem with ueberzug, that it doesn't find the modules or functions. 
Even without vifm, just normal `$ueberzug a.jpeg`  gives the same problem. 
I hope it can be fixed.

Traceback (most recent call last):
  File "/bin/ueberzug", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pillow-simd' distribution was not found and is required by ueberzug

**Comment by seebye** [comment]
Try to reinstall it / try to install pillow-simd.  
Theoretically it should also work with pillow as pillow-simd is a pillow fork which uses hardware features to accelerate some image manipulation operations.

**Comment by dmorady1** [comment]
Thank you for your quick reply. Seems like the version 6.0.0 of pillow-simd doesn't work. 
But the version Version: 5.3.0.post1 does. 
If someone has the same issue.  I have arch linux installed and used the aur to install pillow-simd.
Now I'm using pip.
And now it works again.
