### ISSUE TITLE
Execution fails on Xmonad. Archlinux.

### ISSUE THREAD

**Issue by PittacusOfLorien** [seebye/ueberzug#65]
It throws this error:

> Traceback (most recent call last):
  File "/usr/bin/ueberzug", line 11, in <module>
    load_entry_point('ueberzug==18.1.3', 'console_scripts', 'ueberzug')()
  File "/usr/lib/python3.7/site-packages/ueberzug/ueberzug.py", line 238, in main
    main_layer(options)
  File "/usr/lib/python3.7/site-packages/ueberzug/ueberzug.py", line 183, in main_layer
    window_infos = xutil.gep

**Comment by PittacusOfLorien** [comment]
Traceback (most recent call last):
  File "/usr/bin/ueberzug", line 11, in <module>
    load_entry_point('ueberzug==18.1.2', 'console_scripts', 'ueberzug')()
 File "/usr/lib/python3.7/site-packages/ueberzug/ueberzug.py", line 225, in main
    main_layer(options)
  File "/usr/lib/python3.7/site-packages/ueberzug/ueberzug.py", line 175, in main_layer
    window_infos = xutil.g
File "/usr/lib/python3.7/site-packages/ueberzug/xutil.py", line 159, in get_parent_window_infoset_parent_window_infos()
File "/usr/lib/python3.7/site-packages/ueberzug/xutil.py", line 98, in get_pid_window_id_map
    Xlib.X.AnyPropertyType)
AttributeError: 'NoneType' object has no attribute 'value
