### ISSUE TITLE
The _imaging extension was built for another version of Pillow or PIL

### ISSUE THREAD

**Issue by FrostyX** [seebye/ueberzug#67]
When trying to run `ueberzug` in the command line, I get following error

    /home/jkadlcik/.local/lib/python3.7/site-packages/PIL/Image.py:116: RuntimeWarning: The _imaging extension was buil
    Core version: 6.0.0.post0                                                                                          
    Pillow version: 6.1.0                                                                                              
      warnings.warn(str(v), RuntimeWarning)                                                                            
    Traceback (most recent call last):                                                                                 
      File "/usr/local/bin/ueberzug", line 11, in <module>                                                             
        load_entry_point('ueberzug==18.1.3', 'console_scripts', 'ueberzug')()                                          
      File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point                 
        return get_distribution(dist).load_entry_point(group, name)                                                    
      File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point                
        return ep.load()                                                                                               
      File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load                            
        return self.resolve()                                                                                          
      File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve                         
        module = __import__(self.module_name, fromlist=['__name__'], level=0)                                          
      File "/home/jkadlcik/.local/lib/python3.7/site-packages/ueberzug/ueberzug.py", line 38, in <module>              
        import ueberzug.ui as ui                                                                                       
      File "/home/jkadlcik/.local/lib/python3.7/site-packages/ueberzug/ui.py", line 11, in <module>                    
        import PIL.Image as Image                                                                                      
      File "/home/jkadlcik/.local/lib/python3.7/site-packages/PIL/Image.py", line 101, in <module>                     
        "Pillow version: %s" % (getattr(core, "PILLOW_VERSION", None), __version__)                                    
    ImportError: The _imaging extension was built for another version of Pillow or PIL:                                
    Core version: 6.0.0.post0                                                                                          
    Pillow version: 6.1.0

**Comment by FrostyX** [comment]
Possibly this is a PEBKAC, but I followed the instructions in the readme. Do you need any additional information about the system?

**Comment by FrostyX** [comment]
I've tried to 

    git clone ...
    git checkout 18.1.2
    pip3 install . --user

And it seems to work, so there is probably a bug in the last version.

**Comment by FrostyX** [comment]
Hmm, seems like this issue can be fixed by:

    pip3 uninstall pillow pillow-simd
    pip3 install . --user

**Comment by seebye** [comment]
> The _imaging extension was built for another version of Pillow or PIL:

Seems like you somehow got pillow corrupted or wrongly installed or partly installed or ..

> Hmm, seems like this issue can be fixed by: [...]

Proves my suspicion.
