### ISSUE TITLE
Manual build FreeBSD st ranger

### ISSUE THREAD

**Issue by plasmoduck** [seebye/ueberzug#96]
After manually building on FreeBSD and setting ranger to use ueberzug, I run ranger in st and get these errors and no picture.

Traceback (most recent call last):  File "/usr/local/bin/ueberzug", line 11, in <module> load_entry_point('ueberzug==18.1.5', 'console_scripts', 'ueberzug')()
 File "/usr/local/lib/python3.7/site-packages/ueberzug-18.1.5-py3.7-freebsd-12.1-RELEASE-p3-amd64.egg/ueberzug/__main__.py", line 52, in main  module.main(options)
 File "/usr/local/lib/python3.7/site-packages/ueberzug-18.1.5-py3.7-freebsd-12.1-RELEASE-p3-amd64.egg/ueberzug/layer.py", line 191, in main get_parent_window_infos()
File "/usr/local/lib/python3.7/site-packages/ueberzug-18.1.5-py3.7-freebsd-12.1-RELEASE-p3-amd64.egg/ueberzug/xutil.py", line 178, in get_parent_window_infos
 ppids = get_parent_pids(pid)
File "/usr/local/lib/python3.7/site-packages/ueberzug-18.1.5-py3.7-freebsd-12.1-RELEASE-p3-amd64.egg/ueberzug/xutil.py", line 77, in get_parent_pids  process = process.parent() TypeError: 'Process' object is not callable

**Comment by seebye** [comment]
As stated in the issue I linked in your last issue: bsd isn't supported.
